# Generated by Django 4.2.18 on 2025-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shop',
            field=models.CharField(choices=[('Shop 1', 'Shop 1'), ('Shop 2', 'Shop 2')], max_length=20, null=True),
        ),
    ]
