# Generated by Django 4.2.7 on 2023-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useName', models.CharField(max_length=100, null=True)),
                ('thumbsUppCount', models.IntegerField(null=True)),
                ('thumbsDownCount', models.IntegerField(null=True)),
                ('review', models.TextField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
