# Generated by Django 4.2.7 on 2023-11-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='useName',
            new_name='userName',
        ),
    ]
