version: "3.8"

services:
  # Django app service
  inventar-django:
    build:
      context: ./reviews
      dockerfile: Dockerfile
    image: inert/inventar-django:new
    container_name: inventar-django
    ports:
      - "8000:8000"
    volumes:
      - ./reviews:/app
      - /mnt/c/Local-Shop:/data
    environment:
      - DATABASE_PATH=/data/db.sqlite3
    networks:
      - frontend
      - backend
    command: bash /app/start.sh
    restart: always

  # Vue.js app service
  inventar-vue:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: inert/inventar-vue:new
    container_name: inventar-vue
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - frontend
      - backend
    restart: always

networks:
  backend:
  frontend:
