services:
  inventar-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inert/store:end
    container_name: inventar-app
    ports:
      - "8000:8000"  # Django backend
      - "3000:3000"  # Vue.js frontend
    volumes:
      - ./reviews:/usr/src/app/reviews  
      - ./front:/usr/src/app/front      
    environment:
      DATABASE_PATH: /data/db.sqlite3  
    networks:
      - frontend
      - backend
    restart: always

networks:
  backend:
  frontend:
