FROM python:3.9-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    dos2unix && \
    rm -rf /var/lib/apt/lists/*

COPY . .

RUN dos2unix start.sh && chmod +x start.sh

RUN pip install djangorestframework django-cors-headers

EXPOSE 8000

CMD ["bash", "start.sh"]
